spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update